// ===========================================================================
// INTERIM SHIM — delete when T2's `src/ai/trace/build.ts` lands.
//
// The rendering team consumes `DecisionTraceV1`. Until the ML team publishes
// the builder that produces it, this maps today's `SearchResult` onto the
// contract so the presentation can be built and verified against real
// decisions rather than fixtures.
//
// The rule it follows, without exception: **understate, never invent.** Where
// today's `SearchResult` cannot answer a contract field truthfully, the field
// is left null/empty and the presentation renders nothing for it. There is no
// field in here whose value is guessed.
//
// Three places where that shows, all of which resolve when T2's builder lands:
//
//  1. `rejection` is `null` wherever the current search cannot attribute a
//     cause. The contract says "null iff selected"; this shim knowingly
//     deviates in the safe direction, and `presentation.ts` treats a null
//     reason as "dim it, say nothing".
//  2. `physics` is populated only for candidates that have a `CandidateStat`
//     row. A candidate that was simulated and then dropped (its seeding sim
//     scratched) is *understated* as never simulated, because `stats` no
//     longer carries its numbers.
//  3. `policy: "trick-only"` is a contract literal. It is not yet true of the
//     shipped search — that is T2's change — and nothing renders it.
// ===========================================================================

import type { Candidate } from "../../ai/candidates";
import type { CandidateStat, SearchResult } from "../../ai/shotSearch";
import type {
  DecisionTraceV1,
  FallbackTrace,
  RejectionReason,
  SelectedShotTrace,
  TracedCandidate,
} from "../../ai/trace/contract";
import { DECISION_TRACE_VERSION } from "../../ai/trace/contract";
import type { PlayerId } from "../../game/state";

export interface AdaptContext {
  /** `generateCandidates` output, in generation order. */
  generated: Candidate[];
  player: PlayerId;
  shotIndex: number;
  legalTargets: number[];
  /** Wall clock around the whole `brain.plan` call. */
  totalMs: number;
  hashVerified: boolean;
}

/**
 * Geometric identity of a candidate. `generateCandidates` is pure, so the list
 * re-generated by the planner and the one the search built internally are
 * element-wise identical — but not reference-identical, so `stats` rows are
 * matched back to generation order structurally.
 */
const keyOf = (c: Candidate): string =>
  `${c.kind}|${c.target}|${c.potId}|${c.pocket}|${c.aimPoint.x.toFixed(6)}|${c.aimPoint.y.toFixed(6)}`;

export function adaptSearchResult(
  result: SearchResult,
  ctx: AdaptContext,
): DecisionTraceV1 {
  const t = result.trace;
  const statByKey = new Map<string, CandidateStat>();
  for (const s of result.stats) statByKey.set(keyOf(s.candidate), s);

  const verified = new Set(t?.verifiedIndices ?? []);
  const neuralRan = t?.mode === "neural-hybrid" && !t?.fallbackReason;
  const bestKey = result.best ? keyOf(result.best.candidate) : null;

  const selectedIndex = bestKey === null
    ? null
    : ctx.generated.findIndex((c) => keyOf(c) === bestKey);

  // Ranks the model actually produced, recovered from the stats rows that
  // carry them. A candidate the search never scored has no rank and gets no
  // `neural` block — the presentation then weights it neutrally.
  const candidates: TracedCandidate[] = ctx.generated.map((c, i) => {
    const s = statByKey.get(keyOf(c));
    const isSelected = selectedIndex === i;
    return {
      index: i,
      kind: c.kind,
      // The eligibility partition is T2's; today every generated candidate is
      // eligible, and saying otherwise would be the lie this file exists to
      // avoid.
      eligible: true,
      target: c.target,
      potId: c.potId,
      pocket: c.pocket,
      aimPoint: { x: c.aimPoint.x, y: c.aimPoint.y },
      path: c.path.map((p) => ({ x: p.x, y: p.y })),
      action: { ...c.action },
      neural:
        neuralRan && s?.priorScore !== undefined && s.priorRank !== undefined
          ? { score: s.priorScore, logit: Number.NaN, rank: s.priorRank }
          : null,
      physics: s
        ? {
            // A stats row exists, so this candidate was simulated and did not
            // scratch (scratched candidates are excluded outright by the
            // search before a row is written).
            firstContact: s.potsTarget ? c.target : null,
            legalFirstContact: s.potsTarget,
            scratched: false,
            legalPot: s.potsTarget,
            pocketed: s.potsTarget ? [c.potId] : [],
            railContacts: [],
            railsBeforePot: s.rails,
            contactSequence: [],
            strength: s.strength,
            value: s.value,
            visits: s.visits,
            styleScore: s.styleScore,
          }
        : null,
      rejection: isSelected ? null : rejectionFor({ stat: s, verified: verified.has(i), neuralRan }),
    };
  });

  const selected: SelectedShotTrace | null = result.best
    ? {
        candidateIndex: selectedIndex === -1 ? null : selectedIndex,
        // Today's mixed policy can still select a direct. The contract's type
        // excludes it because T2's trick-only policy makes it impossible; until
        // then the REAL kind is recorded rather than a false trick label.
        kind: result.best.candidate.kind as SelectedShotTrace["kind"],
        rung: "trick-qualified",
        action: { ...result.best.candidate.action },
        path: result.best.candidate.path.map((p) => ({ x: p.x, y: p.y })),
        utility: null,
        reliabilityThreshold: 0.5,
        qualifyingTricks: t?.qualifyingTricks ?? 0,
      }
    : null;

  const neuralRunMs = t?.neuralInferenceMs ?? null;
  return {
    version: DECISION_TRACE_VERSION,
    policy: "trick-only",
    mode: neuralRan ? "neural-hybrid" : "classical-trick-only",
    turn: { player: ctx.player, shotIndex: ctx.shotIndex, legalTargets: ctx.legalTargets },
    model: t?.modelId
      ? { artifact: t.modelId, sha256: "", schema: "", hashVerified: ctx.hashVerified }
      : null,
    budget: {
      physicsUnitsAllowed: result.simulations,
      physicsUnitsSpent: t?.physicsCalls ?? 0,
      safetySimsSpent: 0,
      candidatesGenerated: ctx.generated.length,
      candidatesEligible: ctx.generated.length,
      candidatesConsidered: t?.candidatesConsidered ?? ctx.generated.length,
      physicsVerified: t?.physicsVerified ?? 0,
      prunedByPrior: t?.prunedByPrior ?? 0,
      reservePromotions: t?.reservePromotions ?? 0,
      seedTimedOut: false,
    },
    timing: {
      totalMs: ctx.totalMs,
      neuralEncodeMs: null,
      neuralRunMs,
      // Measured, not modelled: candidate generation is ~2 ms and the ONNX
      // batch is ~5 ms, so the plan's wall clock minus the inference it
      // reports is the physics time to within about one percent. VERIFYING's
      // length is derived from this, so it has to be a real number.
      physicsMs: Math.max(0, ctx.totalMs - (neuralRunMs ?? 0)),
      selectionMs: 0,
    },
    candidates,
    selected,
    fallback: fallbackFor(t?.fallbackReason),
  };
}

function rejectionFor(a: {
  stat: CandidateStat | undefined;
  verified: boolean;
  neuralRan: boolean;
}): RejectionReason | null {
  if (a.stat) {
    // Real physics ran on it and it lost. Both of these are facts the stats
    // row states directly.
    return a.stat.potsTarget ? "lower-utility-than-selected" : "did-not-pot";
  }
  if (!a.verified && !a.neuralRan) {
    // No prior existed, so nothing could have pruned it: the seeding loop
    // simply never reached it inside `simulations`.
    return "budget-exhausted";
  }
  // Pruned-by-prior and budget-exhausted are indistinguishable in today's
  // trace, and a candidate that was simulated then dropped leaves no row that
  // says why. Say nothing rather than guess; the route dims without a caption.
  return null;
}

function fallbackFor(reason: string | undefined): FallbackTrace | null {
  if (!reason) return null;
  const cause: FallbackTrace["cause"] = /no scores/i.test(reason)
    ? "no-scores"
    : /unavailable|absent|404/i.test(reason)
      ? "model-absent"
      : "model-invalid";
  return { from: "neural-hybrid", to: "classical-trick-only", cause, detail: reason };
}
